# Generated by Django 5.1.2 on 2025-08-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament_subject',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='QuizApp.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournament_subject',
            unique_together={('tournament', 'name')},
        ),
    ]
