# Generated by Django 5.1.2 on 2025-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_alter_tournament_subject_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='TournamentEnrollment',
        ),
    ]
