# Generated by Django 5.1.2 on 2025-09-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_subjectplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='Level',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_to_win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
