# Generated by Django 5.1.2 on 2025-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_tournament_level_tournament_prize_to_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
