# Generated by Django 5.1.2 on 2025-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_userprofile_phone_userprofile_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_subject',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
    ]
